
version: '3.8'

services:


  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq_streamio
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - streamio-network

  api-gateway:
    restart: on-failure
    build:
      context: ./apiGateway
    image: api-gateway:latest
    ports:
      - "5000:5000"
    depends_on:
      - live-service
      - comment-service
      - user-service
      - video-service
    env_file:
      - ./apiGateway/.env
    volumes:
      - ./apiGateway:/app
    networks:
      - streamio-network

  comment-service:
    build:
      context: ./commentService
    image: comment-service:latest
    ports:
      - "5003:5003"
      - "50051:50051"
    env_file:
      - ./commentService/.env
    volumes:
      - ./commentService:/app
    networks:
      - streamio-network

  live-service:
    build:
      context: ./liveService
    image: live-service:latest
    ports:
      - "5005:5005"
    env_file:
      - ./liveService/.env
    volumes:
      - ./liveService:/app
    networks:
      - streamio-network


  user-service:
    build:
      context: ./userService
    image: user-service:latest
    ports:
      - "5001:5001"
      - "50054:50054"
    env_file:
      - ./userService/.env
    volumes:
      - ./userService:/app
      - ./videoService:/app/videoService
      
    networks:
      - streamio-network



  video-service:
    build:
      context: ./videoService
    image: video-service:latest
    ports:
      - "5002:5002"
      - "50052:50052"
    depends_on:
      - rabbitmq  
    env_file:
      - ./videoService/.env
    volumes:
      - ./videoService:/app
      - ./videoService/proto:/app/proto
      - ./commentService:/app/commentService
      - ./userService:/app/userService

      
    networks:
      - streamio-network

networks:
  streamio-network:
    driver: bridge
